#!/bin/bash

if [ -z $1 ]
then 
    echo "No branch name provided"
    exit 1
fi

BASEBRANCH="develop"
if [ -n $2 ]
then
    BASEBRANCH=$2
fi

BRANCHNAME=feature/$1

git stash 
git checkout $BASEBRANCH 
git pull --rebase 
git checkout -b $BRANCHNAME 
git stash pop 
git add . 
git commit 
git push origin $BRANCHNAME
#git checkout $BASEBRANCH 
echo "All done"
