#!/bin/bash

if [ -z $1 ]
then 
    echo "No branch name provided"
    exit 1
fi

BASEBRANCH="develop"
if [ -n $2 ]
then
    BASEBRANCH=$2
fi

BRANCHNAME=$1

git stash 
git checkout $BASEBRANCH || echo "Somthing went wrong" && exit 1
git pull || echo "Somthing went wrong" && exit 1
git checkout -b feature/$BRANCHNAME || echo "Somthing went wrong" && exit 1
git stash pop || echo "Somthing went wrong" && exit 1
git add . || echo "Somthing went wrong" && exit 1
git commit || echo "Somthing went wrong" && exit 1
git push origin fearure/$BRANCHNAME || echo "Somthing went wrong" && exit 1
git checkout $BASEBRANCH || echo "Somthing went wrong" && exit 1
echo "All donw"
